### ISSUE TITLE
Question about the training data and validation data

### ISSUE THREAD

**Issue by GWwangshuo** [hubutui/Gleason#3]
I encounter the following problems when try to reimplement you rexperiment:

+ For the validation data which contains 44 images, how do you choose them? Are you randomly select them from all 244 images? 

+ When training the PSPNet, you initialize it with pretrained model on ADE dataset or not? 

+ What's the best mean IoU of your final model when you do validation and how do you solve the problem of unbalanced training samples? 

+ Why train the PSPNet with 6 classes (0 - 5) rather than 4 classes (benign, maglinant(3, 4, 5)) since in the test procedure only exist 4 classes?

**Comment by hubutui** [comment]
1. You could try, we usually do ti randomly.
2. You could try.
3. I don't know the best IoU, because I did not finish the training before the deadline, and submitted it. Nothing is done except described in the code.
4. You could try, I just don't have time.
